# Generated by Django 4.1.3 on 2022-11-30 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_delete_destcommoninfo_destination_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('reviews', models.CharField(blank=True, max_length=250, null=True)),
                ('place', models.ManyToManyField(related_name='place_name', to='course.destination')),
            ],
            options={
                'db_table': 'company',
            },
        ),
    ]
