# Generated by Django 4.1.3 on 2022-12-03 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'booking',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('users_name', models.CharField(blank=True, max_length=250, null=True)),
                ('users_surname', models.CharField(blank=True, max_length=250, null=True)),
                ('nationality', models.CharField(blank=True, max_length=250, null=True)),
                ('address', models.CharField(blank=True, max_length=250, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('wishlist', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.RenameField(
            model_name='destination',
            old_name='place',
            new_name='place_name',
        ),
        migrations.RemoveField(
            model_name='company',
            name='place',
        ),
        migrations.AddField(
            model_name='company',
            name='place_name',
            field=models.ManyToManyField(related_name='companies', to='course.destination'),
        ),
        migrations.CreateModel(
            name='Booking_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(blank=True, max_length=250, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='course.booking')),
                ('destination_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='booking_statuses', to='course.booking')),
            ],
            options={
                'db_table': 'booking_status',
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.destination'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.user'),
        ),
    ]
